version: "3.9"

services:
  finalscheduler:
    build: ./FinalScheduler
    container_name: finalscheduler-FinalScheduler
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - redis
    networks:
      - final-network
    volumes:
      - ./FinalScheduler:/app
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    restart: always
    deploy:
      resources:
        limits:
          memory: 300M  
        reservations:
          memory: 200M

  node-backend:
    build: ./node-backend
    container_name: finalscheduler-node-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - final-network
    volumes:
      - ./node-backend:/app
      - /app/node_modules       
    command: npm start            
    restart: always
    deploy:
      resources:
        limits:
          memory: 350M
        reservations:
          memory: 250M

  redis:
    image: redis:7
    container_name: finalscheduler-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - final-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    deploy:
      resources:
        limits:
          memory: 150M
        reservations:
          memory: 100M

volumes:
  mongo_data:

networks:
  final-network:
    driver: bridge