# node-backend/Dockerfile
FROM node:18-slim
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN mkdir -p public/temp public/uploads
RUN apt-get update && apt-get install -y poppler-utils

EXPOSE 8080

CMD ["npm", "start"]
