# node-backend/Dockerfile
FROM node:18-slim
WORKDIR /app
# node-backend/Dockerfile
FROM node:18-slim
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN mkdir -p public/temp public/uploads
RUN apt-get update && apt-get install -y --no-install-recommends \
    poppler-utils \
    curl \
    && rm -rf /var/lib/apt/lists/*

EXPOSE 8080

CMD ["npm", "start"]
